"""Frasi scritte a mano per il test di Segueo Chat (diverse dai modelli di frase): testo -> etichette attese
(le teste non elencate valgono 'none')."""

CASES = [
    ('la pista è morta, svegliala un po\'', {'strategy': 'rise'}),
    ('sta diventando noioso, alza il tiro', {'strategy': 'rise'}),
    ('la gente sta ballando, continua così con l\'energia', {'strategy': 'steady'}),
    ('facciamo salire piano piano la serata', {'strategy': 'rise'}),
    ('voglio una serata che cresce fino alla fine', {'strategy': 'rise'}),
    ('ora voglio solo roba potentissima', {'strategy': 'peak'}),
    ('è mezzanotte, massima potenza', {'strategy': 'peak'}),
    ('siamo a cena, tieni la musica bassa di energia', {'strategy': 'chill'}),
    ('qualcosa di rilassante per favore', {'strategy': 'chill'}),
    ('calma un attimo, troppa roba', {'strategy': 'chill'}),
    ('alterna un pezzo tosto e uno tranquillo', {'strategy': 'wave'}),
    ('fai dei cambi più morbidi', {'style': 'fade'}),
    ('sfuma meglio i passaggi', {'style': 'fade'}),
    ('voglio stacchi netti sul beat', {'style': 'cut'}),
    ('usa il filtro quando passi al pezzo dopo', {'style': 'filter'}),
    ('scambia i bassi nei cambi', {'style': 'bassswap'}),
    ('chiudi ogni brano con un eco', {'style': 'echo'}),
    ('mixa come fa lumix, cambi a raffica', {'style': 'rapid'}),
    ('fai le transizioni come un dj techno', {'style': 'model-techno'}),
    ('mixa in stile gabry ponte', {'style': 'model'}),
    ('i cambi falli durare di più', {'bars': 'long'}),
    ('passaggi più rapidi', {'bars': 'short'}),
    ('mix lunghissimi stile techno', {'bars': 'verylong', 'style': 'model-techno'}),
    ('metti un po\' di loop ed effetti mentre suona', {'remix': 'on'}),
    ('basta con gli effetti sui brani', {'remix': 'off'}),
    ('niente mashup stasera', {'mashupOpt': 'off'}),
    ('fai partire la serata', {'control': 'start'}),
    ('vai, comincia tu', {'control': 'start'}),
    ('stop, ferma la musica', {'control': 'stop'}),
    ('questo pezzo è brutto, cambialo', {'control': 'mixNow'}),
    ('passa subito al brano dopo', {'control': 'mixNow'}),
    ('quello che hai preparato non va bene, scegline un altro', {'control': 'skip'}),
    ('dopo questa canzone chiudiamo', {'control': 'endAfterCurrent'}),
    ('questa è l\'ultima, poi basta', {'control': 'endAfterCurrent'}),
    ('non chiudere ancora, continua', {'control': 'resume'}),
    ('mettimi golden hour dopo questo', {'queue': 'playNext'}),
    ('poi voglio sentire night drive', {'queue': 'add'}),
    ('aggiungi northern lights alla lista', {'queue': 'add'}),
    ('togli parallel dalla coda', {'queue': 'remove'}),
    ('svuota tutta la coda', {'queue': 'clear'}),
    ('suona solo techno', {'genre': 'include'}),
    ('basta house per stasera', {'genre': 'exclude'}),
    ('non mettere reggaeton', {'genre': 'exclude'}),
    ('ogni tanto mettici un po\' di disco', {'genre': 'add'}),
    ('va bene qualsiasi genere', {'genre': 'clear'}),
    ('stasera solo deep house e più energia', {'genre': 'include', 'strategy': 'rise'}),
    ('niente techno, e fai dissolvenze', {'genre': 'exclude', 'style': 'fade'}),
    ('crea una scaletta di 20 pezzi house', {'set': 'build', 'genre': 'include'}),
    ('preparami un set per un aperitivo in spiaggia', {'set': 'build'}),
    ('mi serve una playlist di un\'ora in crescendo', {'set': 'build', 'strategy': 'rise'}),
    ('fai un mashup tra due pezzi', {'mashup': 'auto'}),
    ('voglio la voce di golden hour sopra la base di glass city', {'mashup': 'explicit'}),
    ('che canzone stai suonando?', {'info': 'now'}),
    ('come si chiama questo pezzo?', {'info': 'now'}),
    ('cosa arriva dopo?', {'info': 'next'}),
    ('perché hai messo questo brano?', {'info': 'why'}),
    ('che c\'è in coda?', {'info': 'queue'}),
    ('come sei messo con le impostazioni?', {'info': 'settings'}),
    ('cosa posso chiederti?', {'info': 'help'}),
    ('per i prossimi due pezzi tagli a raffica', {'style': 'rapid', 'temporary': 'yes'}),
    ('solo per un paio di brani più energia', {'strategy': 'rise', 'temporary': 'yes'}),
    ('per il prossimo pezzo niente techno', {'genre': 'exclude', 'temporary': 'yes'}),
    ('segui la mia lista e basta', {'mode': 'queue'}),
    ('scegli tu cosa mettere', {'mode': 'ai'}),
    ('ciao!', {'talk': 'hello'}),
    ('grazie mille, perfetto', {'talk': 'thanks'}),
    ('che tempo fa a milano?', {'talk': 'offtopic'}),
    ('mi dici una ricetta?', {'talk': 'offtopic'}),
    ('chi vincerà il campionato?', {'talk': 'offtopic'}),
    ('torna alla console', {'view': 'console'}),
    ('più energia, transizioni lunghe e niente house', {'strategy': 'rise', 'bars': 'long', 'genre': 'exclude'}),
    ('parti con qualcosa di tranquillo', {'control': 'start', 'strategy': 'chill'}),
    ('ferma tutto e svuota la coda', {'control': 'stop', 'queue': 'clear'}),
    ('alza l\'energia e metti glass city come prossimo', {'strategy': 'rise', 'queue': 'playNext'}),
    ('la serata deve partire soft e poi esplodere', {'strategy': 'rise'}),
    ('dammi qualcosa di più tranquillo e con cambi morbidi', {'strategy': 'chill', 'style': 'fade'}),
    ('rendila più ballabile', {'strategy': 'rise'}),
    ('troppo forte, abbassa un po\' il ritmo', {'strategy': 'chill'}),
    ('cambi più secchi', {'style': 'cut'}),
    ('attiva i mashup automatici', {'mashupOpt': 'on'}),
]
